FREEZE_FUNC: "none_func"
NUM_EPOCHS: 70
N_CLUSTERS: 30
WARMUPS: 0
DECREASE_CENTER: 1
ADD_SOURCE_IDS: True
CLUSTERING: True
SPLIT_SOURCE: 100
SECOND_ROUND:
  CRITERION:
    FUNC: weighted_cross_entropy_with_logits
    reduce:

