FREEZE_FUNC:
  FUNC: "none_func"
  exclude_layers: [ ]
NUM_EPOCHS: 120
BATCHES_PER_EPOCH: 50
SCHDULER: False
SECOND_ROUND:
  TRAINING_POLICY:
    FUNC: "PreDefinedFineTunePolicy"
    optimizer: optimizer
    architecture: architecture
    as_class: True

