EXP_NAME: "policy_finetune3"
EXP_DIR: "/home/dsi/shaya/dart_results/policy_fintune3/experiment_0/"
FREEZE_FUNC:
  FUNC: "none_func"
  exclude_layers: []
NUM_EPOCHS: 120
BATCHES_PER_EPOCH: 50
TRAINING_POLICY:
  FUNC: "FineTunePolicy"
  return_to_ckpt: False

