FREEZE_FUNC:
  FUNC: "none_func"
NUM_EPOCHS: 120
BATCHES_PER_EPOCH: 50
SCHDULER: False
SECOND_ROUND:
  TRAINING_POLICY:
    FUNC: "FineTunePolicy"
    return_to_ckpt: False
    optimizer: optimizer
    architecture: architecture
    as_class: True