EXP_NAME: "policy_finetune2"
EXP_DIR: "/home/dsi/shaya/dart_results/policy_fintune2/experiment_0/"
FREEZE_FUNC:
  FUNC: "none_func"
  exclude_layers: []
NUM_EPOCHS: 120
BATCHES_PER_EPOCH: 50
TRAINING_POLICY:
  FUNC: "FineTunePolicy"
  return_to_ckpt: True
SCHDULER:
  FUNC: DecreasingOnPlateauOfVal
  initial: 0.002
  multiplier: 0.7

