NUM_EPOCHS: 60
SOFT: False
SPOT: True
FREEZE_FUNC: "freeze_model_spottune"
OPTIMIZER:
  FUNC: Adam
ADD_SOURCE_IDS: True
SECOND_ROUND:
  SAMPLE_FUNC:
    FUNC: 'load_by_gradual_id'
    batches_per_epoch: batches_per_epoch
    batch_size: batch_size