EXP_NAME: "unfreeze_first_ts_2"
EXP_DIR: '/home/dsi/shaya/dart_results/unfreeze_first_ts_2/experiment_0/'
FREEZE_FUNC:
  FUNC: "freeze_model"
  exclude_layers: ['init_path.0', 'init_path.1']
NUM_EPOCHS: 60
