NUM_EPOCHS: 20
BATCHES_PER_EPOCH: 100
ADD_SOURCE_IDS: True
FREEZE_FUNC:
  FUNC: "freeze_model"
  exclude_layers: [ 'init_path', 'down','bottleneck' ]
UNSUP: True
OPTIMIZER:
  FUNC: Adam
  lr: 0.00001
CKPT_NAME: "model_adam"
MSM: True
TRAIN_FUNC:
  FUNC: train_unsup
  n_clusters: 20
TRAIN_STEP_FUNC:
  FUNC: train_step_unsup
  target_domain: target
  dist_loss_lambda: 0.1
SECOND_ROUND:
  CRITERION:
    FUNC: weighted_cross_entropy_with_logits
    reduce:


